export enum CommercialType {
  BROWN_RESOURCE_DISCOUNT = 'BROWN_RESOURCE_DISCOUNT',
  GRAY_RESOURCE_DISCOUNT = 'GRAY_DISCOUNT_RESOURCE',
  ANY_BROWN_RESOURCE = 'ANY_BROWN_RESOURCE',
  ANY_GRAY_RESOURCE = 'ANY_GRAY_RESOURCE',
  COINS = 'COINS',
  COINS_PER_CARD = 'COINS_PER_CARD',
  COINS_PER_WONDER = 'COINS_PER_WONDER',
}
