export enum GuildType {
  VICTORY_POINTS_PER_WONDER = 'VICTORY_POINTS_PER_WONDER',
  VICTORY_POINTS_PER_COINS = 'VICTORY_POINTS_PER_COINS',
  VICTORY_POINTS_AND_COINS_PER_CARD_TYPE = 'VICTORY_POINTS_AND_COINS_PER_CARD_TYPE',
}
