export enum ScienceType {
  WHEEL = 'WHEEL',
  MORTAR = 'MORTAR',
  QUILL = 'QUILL',
  GYROSCOPE = 'GYROSCOPE',
  SUN_DIAL = 'SUN_DIAL',
  PENDULUM = 'PENDULUM',
  LAW = 'LAW',
}

export enum ScienceProgressToken {
  AGRICULTURE = 'AGRICULTURE',
  ARCHITECTURE = 'ARCHITECTURE',
  ECONOMY = 'ECONOMY',
  LAW = 'LAW',
  MASONRY = 'MASONRY',
  MATHEMATICS = 'MATHEMATICS',
  PHILOSOPHY = 'PHILOSOPHY',
  STRATEGY = 'STRATEGY',
  THEOLOGY = 'THEOLOGY',
  URBANISM = 'URBANISM',
}
